// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface BackToDraftReferralBody {
    institutionIdType: ReferralExchange.InstitutionIdType;
    /** The institution ID */
    institutionId: string;
}
