/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface BackToDraftReferralBody {
    /** The institution ID */
    institutionId: string;
}
