/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         cancelNote: "cancelNote",
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface CancelReferralReq {
    /** UIN of the person cancelling the referral, if available */
    cancelledByUin?: string;
    /** Name of the person cancelling the referral, if available */
    cancelledByName?: string;
    /** Reason for cancelling the referral */
    cancelNote: string;
    institutionIdType: ReferralExchange.InstitutionIdType;
    /** The institution ID */
    institutionId: string;
}
