/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface UpdatingReferralsDeleteRequest {
    /**
     * The type of institution ID
     */
    institutionIdType: ReferralExchange.InstitutionIdType;
    /**
     * The institution ID
     */
    institutionId: string;
}
