// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         formId: "formId"
 *     }
 */
export interface SubmitFormsgWebhooksRequest {
    formId: string;
}
