// This file was auto-generated by Fern from our API Definition.

/** Patient gender */
export const CreateLinkReqUpsertPatientGender = {
    Male: "Male",
    Female: "Female",
} as const;
export type CreateLinkReqUpsertPatientGender =
    (typeof CreateLinkReqUpsertPatientGender)[keyof typeof CreateLinkReqUpsertPatientGender];
