// This file was auto-generated by Fern from our API Definition.

/** Patient residential status */
export const CreateLinkReqUpsertResidentialStatus = {
    Sc: "SC",
    Pr: "PR",
    Foreigner: "Foreigner",
} as const;
export type CreateLinkReqUpsertResidentialStatus =
    (typeof CreateLinkReqUpsertResidentialStatus)[keyof typeof CreateLinkReqUpsertResidentialStatus];
