/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Patient gender
 */
export type CreateLinkReqUpsertPatientGender = "Male" | "Female";
export const CreateLinkReqUpsertPatientGender = {
    Male: "Male",
    Female: "Female",
} as const;
