/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         idType: "mcr"
 *     }
 */
export interface ApiHoldingControllerGetReferrersRequest {
    idType: ReferralExchange.ReferrerIdType;
    /**
     * Filter by whitelisting status. true = whitelisted only, false = unwhitelisted only, omit = all.
     */
    whitelisted?: boolean;
}
