/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         refererInstitutionId: "refererInstitutionId",
 *         refererInstitutionName: "refererInstitutionName",
 *         referrerId: "referrerId",
 *         referrerName: "referrerName",
 *         referrerIdType: "referrerIdType"
 *     }
 */
export interface CreateLinkReqUpsert {
    /** HCI code of the institution authoring this referral. */
    refererInstitutionId: string;
    /** Name of the institution authoring this referral. */
    refererInstitutionName: string;
    /** MCR number of the doctor authoring this referral. */
    referrerId: string;
    /** Name of the doctor authoring this referral. */
    referrerName: string;
    /** Type of the referrer ID */
    referrerIdType: string;
}
