/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         referrerInstitutionId: "referrerInstitutionId",
 *         referrerInstitutionName: "referrerInstitutionName",
 *         referrerId: "referrerId",
 *         referrerIdType: "mcr",
 *         referrerName: "referrerName"
 *     }
 */
export interface CreateLinkReqUpsert {
    /** HCI code of the institution authoring this referral. */
    referrerInstitutionId: string;
    /** Name of the institution authoring this referral. */
    referrerInstitutionName: string;
    /** Id of the doctor authoring this referral. */
    referrerId: string;
    referrerIdType: ReferralExchange.ReferrerIdType;
    /** Name of the doctor authoring this referral. */
    referrerName: string;
    /** Email of the doctor authoring this referral. */
    referrerEmail?: string;
    /** Contact number of the doctor authoring this referral. */
    referrerContactNumber?: string;
    /** Patient UIN, e.g. NRIC or FIN */
    patientUin?: string;
    /** Patient name */
    patientName?: string;
    /** Patient phone number - only Singaporean accepted for now */
    patientPhoneNumber?: string;
    /** Patient date of birth */
    patientDob?: string;
    /** Patient gender */
    patientGender?: ReferralExchange.CreateLinkReqUpsertPatientGender;
}
