// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as ReferralExchange from "../../../index.js";

export declare namespace Offerings {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Offerings {
    protected readonly _options: Offerings.Options;

    constructor(_options: Offerings.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {ReferralExchange.ListOfferingsRequest} request
     * @param {Offerings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ReferralExchange.UnauthorizedError}
     *
     * @example
     *     await client.offerings.list({
     *         referrerId: "referrerId",
     *         referrerIdType: "mcr",
     *         referrerInstitutionId: "referrerInstitutionId"
     *     })
     */
    public list(
        request: ReferralExchange.ListOfferingsRequest,
        requestOptions?: Offerings.RequestOptions,
    ): core.HttpResponsePromise<ReferralExchange.OfferingWithAllowedDto[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: ReferralExchange.ListOfferingsRequest,
        requestOptions?: Offerings.RequestOptions,
    ): Promise<core.WithRawResponse<ReferralExchange.OfferingWithAllowedDto[]>> {
        const { referrerId, referrerIdType, referrerInstitutionId, patientPostalCode } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.referrerId = referrerId;
        _queryParams.referrerIdType = referrerIdType;
        _queryParams.referrerInstitutionId = referrerInstitutionId;
        if (patientPostalCode != null) {
            _queryParams.patientPostalCode = patientPostalCode;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ReferralExchangeEnvironment.SmartCms,
                "api/v1/offerings",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as ReferralExchange.OfferingWithAllowedDto[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new ReferralExchange.UnauthorizedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ReferralExchangeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ReferralExchangeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ReferralExchangeTimeoutError("Timeout exceeded when calling GET /api/v1/offerings.");
            case "unknown":
                throw new errors.ReferralExchangeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {ReferralExchange.ApiHoldingControllerGetRecommendedOfferingRequest} request
     * @param {Offerings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ReferralExchange.UnauthorizedError}
     * @throws {@link ReferralExchange.NotFoundError}
     *
     * @example
     *     await client.offerings.apiHoldingControllerGetRecommendedOffering({
     *         category: "aac",
     *         postalCode: "postalCode"
     *     })
     */
    public apiHoldingControllerGetRecommendedOffering(
        request: ReferralExchange.ApiHoldingControllerGetRecommendedOfferingRequest,
        requestOptions?: Offerings.RequestOptions,
    ): core.HttpResponsePromise<ReferralExchange.OfferingDto> {
        return core.HttpResponsePromise.fromPromise(
            this.__apiHoldingControllerGetRecommendedOffering(request, requestOptions),
        );
    }

    private async __apiHoldingControllerGetRecommendedOffering(
        request: ReferralExchange.ApiHoldingControllerGetRecommendedOfferingRequest,
        requestOptions?: Offerings.RequestOptions,
    ): Promise<core.WithRawResponse<ReferralExchange.OfferingDto>> {
        const { category, postalCode } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.category = category;
        _queryParams.postalCode = postalCode;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ReferralExchangeEnvironment.SmartCms,
                "api/v1/offerings/recommended",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as ReferralExchange.OfferingDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new ReferralExchange.UnauthorizedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 404:
                    throw new ReferralExchange.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ReferralExchangeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ReferralExchangeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ReferralExchangeTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/offerings/recommended.",
                );
            case "unknown":
                throw new errors.ReferralExchangeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {ReferralExchange.ListTimeslotsOfferingsRequest} request
     * @param {Offerings.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ReferralExchange.UnauthorizedError}
     *
     * @example
     *     await client.offerings.listTimeslots({
     *         offeringId: "offeringId",
     *         from: 1.1
     *     })
     */
    public listTimeslots(
        request: ReferralExchange.ListTimeslotsOfferingsRequest,
        requestOptions?: Offerings.RequestOptions,
    ): core.HttpResponsePromise<ReferralExchange.Timeslot[]> {
        return core.HttpResponsePromise.fromPromise(this.__listTimeslots(request, requestOptions));
    }

    private async __listTimeslots(
        request: ReferralExchange.ListTimeslotsOfferingsRequest,
        requestOptions?: Offerings.RequestOptions,
    ): Promise<core.WithRawResponse<ReferralExchange.Timeslot[]>> {
        const { offeringId, from: from_, isSubsidised } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.from = from_.toString();
        if (isSubsidised != null) {
            _queryParams.isSubsidised = isSubsidised.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ReferralExchangeEnvironment.SmartCms,
                `api/v1/offerings/${core.url.encodePathParam(offeringId)}/timeslots`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as ReferralExchange.Timeslot[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new ReferralExchange.UnauthorizedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ReferralExchangeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ReferralExchangeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ReferralExchangeTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/offerings/{offeringId}/timeslots.",
                );
            case "unknown":
                throw new errors.ReferralExchangeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { Authorization: apiKeyValue };
    }
}
