/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface AcceptReferralBody {
    /** Appointment time, in milliseconds since epoch. */
    appointmentTime?: number;
    /** Note content */
    noteContent?: string;
}
