// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId"
 *     }
 */
export interface AcceptReferralBody {
    /** Referral ID */
    referralId: string;
    /** Appointment time, in milliseconds since epoch. */
    appointmentTime?: number;
    /** Note content */
    noteContent?: string;
}
