/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface AcceptReferralBody {
    /** Appointment time, in milliseconds since epoch. */
    appointmentTime?: number;
    /** Note content */
    noteContent?: string;
    /** The institution ID */
    institutionId: string;
}
