// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId",
 *         timeslotStartAt: 1714857600000
 *     }
 */
export interface AmendReferralReq {
    /** Referral ID */
    referralId: string;
    /** New timeslot start time, in milliseconds since epoch. */
    timeslotStartAt: number;
}
