/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         timeslotStartAt: 1714857600000,
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface AmendReferralReq {
    /** New timeslot start time, in milliseconds since epoch. */
    timeslotStartAt: number;
    /** The institution ID */
    institutionId: string;
}
