/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface CancelReferralReq {
    /** UIN of the person cancelling the referral, if available */
    cancelledByUin?: string;
    /** Name of the person cancelling the referral, if available */
    cancelledByName?: string;
    /** Optional note to save when cancelling the referral */
    cancelNote?: string;
    /** The institution ID */
    institutionId: string;
}
