// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId"
 *     }
 */
export interface CancelReferralReq {
    /** Referral ID */
    referralId: string;
    /** UIN of the person cancelling the referral, if available */
    cancelledByUin?: string;
    /** Name of the person cancelling the referral, if available */
    cancelledByName?: string;
    /** Optional note to save when cancelling the referral */
    cancelNote?: string;
}
