/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface CancelReferralReq {
    /** UIN of the person cancelling the referral, if available */
    cancelledByUin?: string;
    /** Name of the person cancelling the referral, if available */
    cancelledByName?: string;
}
