// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId"
 *     }
 */
export interface DeleteReferralsRequest {
    /** Referral ID */
    referralId: string;
}
