/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         appointmentTime: 1714857600000
 *     }
 */
export interface EaConfirmReferralBody {
    /** Appointment time, in milliseconds since epoch. */
    appointmentTime: number;
    /** Note content */
    noteContent?: string;
}
