/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         rejectionMessage: "rejectionMessage"
 *     }
 */
export interface EaRejectReferralBody {
    /** Rejection message */
    rejectionMessage: string;
}
