// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../../../../index.js";

/**
 * @example
 *     {
 *         referralId: "referralId"
 *     }
 */
export interface GetReferralsRequest {
    /** Referral ID */
    referralId: string;
    additionalField?: ReferralExchange.AdditionalReferralField | ReferralExchange.AdditionalReferralField[];
}
