/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         requesterIdentifier: "requester@example.com",
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface ReferralsGetRequest {
    additionalField?: ReferralExchange.AdditionalReferralField | ReferralExchange.AdditionalReferralField[];
    /**
     * Identifier for the individual requesting the referral. Preferred to be an email.
     */
    requesterIdentifier: string;
    /**
     * The type of institution ID
     */
    institutionIdType: ReferralExchange.InstitutionIdType;
    /**
     * The institution ID
     */
    institutionId: string;
}
