/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         requesterIdentifier: "requester@example.com"
 *     }
 */
export interface ReferralsGetRequest {
    additionalField?: ReferralExchange.AdditionalReferralField | ReferralExchange.AdditionalReferralField[];
    /**
     * Identifier for the individual requesting attachments/link/url. Required when requesting attachments/link/url. Preferred to be an email.
     */
    requesterIdentifier?: string;
}
