/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ReferralsListByInstitutionRequest {
    /**
     * Offset for pagination
     */
    offset?: number;
    /**
     * Number of items per page
     */
    pageSize?: number;
    status?: ReferralExchange.ReferralStatusFilter | ReferralExchange.ReferralStatusFilter[];
    /**
     * To filter by the institution's role in the referral. e.g. For outbound referrals, use "sender'
     */
    role?: ReferralExchange.ReferralRole;
    /**
     * To filter by the referrer ID
     */
    referrerId?: string;
    /**
     * Type of ID specified in referrerId. Use together with `referrerId` to filter based on referrer.
     */
    referrerIdType?: ReferralExchange.ReferrerIdType;
    /**
     * To filter by the patient UIN
     */
    patientUin?: string;
}
