/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         offset: 1.1,
 *         pageSize: 1.1,
 *         hciCode: "hciCode"
 *     }
 */
export interface ReferralsListRequest {
    /**
     * Offset for pagination
     */
    offset: number;
    /**
     * Number of items per page
     */
    pageSize: number;
    /**
     * To identify the requesting institution
     */
    hciCode: string;
    status?: ReferralExchange.ReferralsListRequestStatusItem | ReferralExchange.ReferralsListRequestStatusItem[];
    /**
     * To filter by the institution's role in the referral. e.g. For outbound referrals, use "sender'
     */
    role?: ReferralExchange.ReferralsListRequestRole;
}
