// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId",
 *         rejectionMessage: "rejectionMessage"
 *     }
 */
export interface RejectReferralBody {
    /** Referral ID */
    referralId: string;
    /** Rejection message */
    rejectionMessage: string;
}
