/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         uin: "uin",
 *         offeringId: "offeringId"
 *     }
 */
export interface EligibilityGetRequest {
    /**
     * ID of the referring individual. Use together with `referralIdType` and `referrerInstitutionId` to filter based on referrer.
     */
    referrerId?: string;
    referrerIdType?: ReferralExchange.ReferrerIdType;
    /**
     * ID of the referring institution. Use together with `referrerId` and `referrerIdType` to filter based on referrer.
     */
    referrerInstitutionId?: string;
    /**
     * Postal code of the patient
     */
    patientPostalCode?: string;
    /**
     * Patient's unique identity number (NRIC or FIN)
     */
    uin: string;
    /**
     * Referral destination to check eligibility for
     */
    offeringId: string;
}
