/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         uin: "uin",
 *         offeringId: "offeringId"
 *     }
 */
export interface EligibilityGetRequest {
    /**
     * Patient's unique identity number (NRIC or FIN)
     */
    uin: string;
    /**
     * Referral destination to check eligibility for
     */
    offeringId: string;
}
