// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../../../../index.js";

/**
 * @example
 *     {
 *         referrerId: "referrerId",
 *         referrerIdType: "mcr",
 *         referrerInstitutionId: "referrerInstitutionId",
 *         uin: "uin",
 *         offeringId: "offeringId"
 *     }
 */
export interface GetEligibilityRequest {
    /** ID of the referring individual. */
    referrerId: string;
    referrerIdType: ReferralExchange.ReferrerIdType;
    /** ID of the referring institution. */
    referrerInstitutionId: string;
    /** Postal code of the patient */
    patientPostalCode?: string;
    /** Patient's unique identity number (NRIC or FIN) */
    uin: string;
    /** Referral destination to check eligibility for */
    offeringId: string;
}
