/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         postalCode: "postalCode"
 *     }
 */
export interface ApiHoldingControllerGetRecommendedOfferingRequest {
    /**
     * Offering category to retrieve recommendation for
     */
    category: "aac";
    /**
     * Postal code of the patient to retrieve recommendation for
     */
    postalCode: string;
}
