// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../../../../index.js";

/**
 * @example
 *     {
 *         referrerId: "referrerId",
 *         referrerIdType: "mcr",
 *         referrerInstitutionId: "referrerInstitutionId"
 *     }
 */
export interface ListOfferingsRequest {
    /** ID of the referring individual. */
    referrerId: string;
    referrerIdType: ReferralExchange.ReferrerIdType;
    /** ID of the referring institution. */
    referrerInstitutionId: string;
    /** Postal code of the patient */
    patientPostalCode?: string;
}
