/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         referrerId: "referrerId",
 *         referrerIdType: "mcr",
 *         referrerInstitutionId: "referrerInstitutionId"
 *     }
 */
export interface OfferingsListRequest {
    /**
     * ID of the referring individual.
     */
    referrerId: string;
    referrerIdType: ReferralExchange.ReferrerIdType;
    /**
     * ID of the referring institution.
     */
    referrerInstitutionId: string;
    /**
     * Postal code of the patient
     */
    patientPostalCode?: string;
}
