/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {}
 */
export interface OfferingsListRequest {
    /**
     * ID of the referring individual. Use together with `referralIdType` and `referrerInstitutionId` to filter based on referrer.
     */
    referrerId?: string;
    referrerIdType?: ReferralExchange.ReferrerIdType;
    /**
     * ID of the referring institution. Use together with `referrerId` and `referrerIdType` to filter based on referrer.
     */
    referrerInstitutionId?: string;
}
