/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         from: 1.1,
 *         isSubsidised: true
 *     }
 */
export interface OfferingsListTimeslotsRequest {
    from: number;
    isSubsidised: boolean;
}
