/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AdditionalReferralField = "attachments" | "url" | "link" | "appointments" | "nehrForm";
export const AdditionalReferralField = {
    Attachments: "attachments",
    Url: "url",
    Link: "link",
    Appointments: "appointments",
    NehrForm: "nehrForm",
} as const;
