// This file was auto-generated by Fern from our API Definition.

export const AdditionalReferralField = {
    Attachments: "attachments",
    Url: "url",
    Link: "link",
    Appointments: "appointments",
} as const;
export type AdditionalReferralField = (typeof AdditionalReferralField)[keyof typeof AdditionalReferralField];
