// This file was auto-generated by Fern from our API Definition.

export interface AppointmentDto {
    status: AppointmentDto.Status;
    institutionName?: string | null;
    specialtyName?: string | null;
    subSpecialtyName?: string | null;
    visitDateTime: string;
    isDischarged: boolean;
}

export namespace AppointmentDto {
    export const Status = {
        Booked: "booked",
        Actualized: "actualized",
        NoShow: "noShow",
        Cancelled: "cancelled",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
