// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface AppointmentDto {
    status: ReferralExchange.AppointmentDtoStatus;
    institutionName?: string | undefined;
    specialtyName?: string | undefined;
    subSpecialtyName?: string | undefined;
    visitDateTime: string;
    isDischarged: boolean;
    location?: string | undefined;
}
