/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface AppointmentDto {
    status: ReferralExchange.AppointmentDtoStatus;
    institutionName?: string;
    specialtyName?: string;
    subSpecialtyName?: string;
    visitDateTime: string;
    isDischarged: boolean;
}
