// This file was auto-generated by Fern from our API Definition.

export const AppointmentDtoStatus = {
    Scheduled: "scheduled",
    Actualized: "actualized",
    NoShow: "no-show",
    Cancelled: "cancelled",
    Unknown: "unknown",
} as const;
export type AppointmentDtoStatus = (typeof AppointmentDtoStatus)[keyof typeof AppointmentDtoStatus];
