/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AppointmentDtoStatus = "scheduled" | "actualized" | "no-show" | "cancelled" | "unknown";
export const AppointmentDtoStatus = {
    Scheduled: "scheduled",
    Actualized: "actualized",
    NoShow: "no-show",
    Cancelled: "cancelled",
    Unknown: "unknown",
} as const;
