// This file was auto-generated by Fern from our API Definition.

export const CoreReferralStatus = {
    Draft: "draft",
    Pending: "pending",
    Confirmed: "confirmed",
    Rejected: "rejected",
    Cancelled: "cancelled",
    SenderActionRequired: "sender-action-required",
} as const;
export type CoreReferralStatus = (typeof CoreReferralStatus)[keyof typeof CoreReferralStatus];
