/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface CreateReferrerReq {
    /** Institution ID for the referrer(s). */
    institutionId: string;
    /** List of referrer IDs to add. */
    referrerIds: string[];
    referrerIdType: ReferralExchange.ReferrerIdType;
    /** Whether the referrer is SingHealth whitelisted. */
    singhealthWhitelisted: boolean;
}
