// This file was auto-generated by Fern from our API Definition.

/** Patient address geographical area */
export const CreateAddressReqGeographicalArea = {
    North: "North",
    South: "South",
    East: "East",
    West: "West",
} as const;
export type CreateAddressReqGeographicalArea =
    (typeof CreateAddressReqGeographicalArea)[keyof typeof CreateAddressReqGeographicalArea];
