/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface CreateReferralFormReq {
    formMetadata: ReferralExchange.FormMetadata;
    /** Override existing form by the passed-in metadata */
    override: boolean;
}
