/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateAddressReq {
    /** Patient postal code */
    postalCode: string;
    /** Patient address block number */
    block: string;
    /** Patient address street name */
    streetName: string;
    /** Patient address floor number */
    floorNumber: string;
    /** Patient address unit number */
    unitNumber: string;
}
