// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface CreateReferralFormReq {
    formMetadata: ReferralExchange.FormMetadata;
    /** Override existing form by the passed-in metadata */
    override: boolean;
}
