// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface CreateAddressReq {
    /** Patient postal code */
    postalCode: string;
    /** Patient address block number */
    block: string;
    /** Patient address street name */
    streetName: string;
    /** Patient address floor number */
    floorNumber: string;
    /** Patient address unit number */
    unitNumber: string;
    /** Patient address building name */
    buildingName: string;
    /** Patient address city */
    city: string;
    /** Patient address geographical area */
    geographicalArea: ReferralExchange.CreateAddressReqGeographicalArea;
    /** Patient address country */
    country: ReferralExchange.CreateAddressReqCountry;
}
