// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface EligibilityRes {
    referral: ReferralExchange.ReferralEligibility;
    /** Will be present if isAllowed for referral is true */
    subsidy?: ReferralExchange.SubsidyEligibility;
}
