/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface EligibilityRes {
    referral: ReferralExchange.ReferralEligibility;
    subsidy: ReferralExchange.SubsidyEligibility;
}
