/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EligibilityReasonDto {
    /** Human-readable message explaining the eligibility failure */
    message?: string;
    /** Actionable information for the user, e.g. who to contact for access */
    action?: string;
}
