/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EmailReminderSignature {
    /** Name of the person signing the email */
    name: string;
    /** Title of the person signing the email */
    title: string;
}
