/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface Form {
    id: string;
    url: string;
    description: string;
    isFilled: boolean;
    formResponses: ReferralExchange.FormResponse[];
}
