// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface Form {
    id: string;
    url: string;
    description: string;
    isFilled: boolean;
    formResponses: ReferralExchange.FormResponse[];
}
