// This file was auto-generated by Fern from our API Definition.

export interface FormResponse {
    question: string;
    id: string;
    answer: FormResponse.Answer;
}

export namespace FormResponse {
    export type Answer = string | string[] | number;
}
