/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface FormResponse {
    question: string;
    id: string;
    answer: ReferralExchange.FormResponseAnswer;
}
