// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface Form {
    id: string;
    url: string;
    description: string;
    remark?: string | undefined;
    fields?: Record<string, unknown>[] | undefined;
    version?: number | undefined;
    migrated?: boolean | undefined;
    isFilled: boolean;
    formResponses: ReferralExchange.FormResponse[];
}
