/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface FullReferralDto {
    id: string;
    sender: ReferralExchange.InstitutionCoreDto;
    senderSystem: ReferralExchange.System;
    offering: ReferralExchange.OfferingDto;
    patient: ReferralExchange.GetReferralPatientDto;
    referringDoctor: ReferralExchange.ReferringDoctorDto;
    isSubsidised: boolean;
    isUrgent: boolean;
    /** Created at (ISO datetime) */
    createdAt: string;
    formResponses: ReferralExchange.FormResponse[];
    /** List of forms required to complete the referral */
    forms?: ReferralExchange.Form[];
    attachments: ReferralExchange.AttachmentDto[];
    /** URL to view the referral */
    url?: string;
    status: ReferralExchange.FullReferralDtoStatus;
    /** Timeslot start time (ISO datetime) */
    timeslotStartAt?: string;
    notes: ReferralExchange.NoteDto[];
    timelineEvents: ReferralExchange.TimelineEventDto[];
    links: ReferralExchange.ReferralLinkDto[];
}
