/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface FullReferralDtoReferringDoctor {
    mcr?: string;
    name?: string;
    email?: string;
    contactNumber?: string;
}
