// This file was auto-generated by Fern from our API Definition.

/** Clinic type */
export const FullReferralDtoClinicType = {
    ChasOnly: "CHAS-only",
    ChasAndHsg: "CHAS and HSG",
    ChasAndHealthierSg: "CHAS and Healthier SG",
} as const;
export type FullReferralDtoClinicType = (typeof FullReferralDtoClinicType)[keyof typeof FullReferralDtoClinicType];
