// This file was auto-generated by Fern from our API Definition.

/** Patient residential status */
export const GetReferralPatientDtoResidentialStatus = {
    Sc: "SC",
    Pr: "PR",
    Foreigner: "Foreigner",
} as const;
export type GetReferralPatientDtoResidentialStatus =
    (typeof GetReferralPatientDtoResidentialStatus)[keyof typeof GetReferralPatientDtoResidentialStatus];
