// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface GetReferralPatientDto {
    /** Patient UIN, e.g. NRIC or FIN */
    uin: string;
    /** Patient name */
    name: string;
    /** Patient phone number - only Singaporean accepted for now */
    phoneNumber: string;
    /** Patient date of birth */
    dob: string;
    /** Patient gender */
    gender: GetReferralPatientDto.Gender;
    address?: ReferralExchange.CreateAddressReq;
    /** Patient residential status */
    residentialStatus?: GetReferralPatientDto.ResidentialStatus;
    /** Patient Healthier SG (HSG) enrolment status */
    isHsgEnrolled?: boolean;
    /** Current CHAS status */
    chasStatus: string;
}

export namespace GetReferralPatientDto {
    /** Patient gender */
    export const Gender = {
        Male: "Male",
        Female: "Female",
    } as const;
    export type Gender = (typeof Gender)[keyof typeof Gender];
    /** Patient residential status */
    export const ResidentialStatus = {
        Sc: "SC",
        Pr: "PR",
        Foreigner: "Foreigner",
    } as const;
    export type ResidentialStatus = (typeof ResidentialStatus)[keyof typeof ResidentialStatus];
}
