// This file was auto-generated by Fern from our API Definition.

/** Patient gender */
export const GetReferralPatientDtoGender = {
    Male: "Male",
    Female: "Female",
} as const;
export type GetReferralPatientDtoGender =
    (typeof GetReferralPatientDtoGender)[keyof typeof GetReferralPatientDtoGender];
