/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Patient gender
 */
export type GetReferralPatientDtoGender = "Male" | "Female";
export const GetReferralPatientDtoGender = {
    Male: "Male",
    Female: "Female",
} as const;
