// This file was auto-generated by Fern from our API Definition.

/** Patient race */
export const GetReferralPatientDtoRace = {
    Chinese: "Chinese",
    Malay: "Malay",
    Indian: "Indian",
    Others: "Others",
} as const;
export type GetReferralPatientDtoRace = (typeof GetReferralPatientDtoRace)[keyof typeof GetReferralPatientDtoRace];
