/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface GetReferralPatientDto {
    /** Patient UIN, e.g. NRIC or FIN */
    uin: string;
    /** Patient name */
    name: string;
    /** Patient phone number - only Singaporean accepted for now */
    phoneNumber: string;
    /** Patient date of birth */
    dob: string;
    /** Patient gender */
    gender: ReferralExchange.GetReferralPatientDtoGender;
    address?: ReferralExchange.CreateAddressReq;
    /** Patient residential status */
    residentialStatus?: ReferralExchange.GetReferralPatientDtoResidentialStatus;
    /** Patient Healthier SG (HSG) enrolment status */
    isHsgEnrolled?: boolean;
    /** Current CHAS status */
    chasStatus?: string;
}
