/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of institution ID
 */
export type InstitutionIdType = "hci" | "uen";
export const InstitutionIdType = {
    Hci: "hci",
    Uen: "uen",
} as const;
