// This file was auto-generated by Fern from our API Definition.

/** The type of institution ID */
export const InstitutionIdType = {
    Hci: "hci",
} as const;
export type InstitutionIdType = (typeof InstitutionIdType)[keyof typeof InstitutionIdType];
