/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InstitutionCoreDto {
    hciCode: string;
    name: string;
    block: string;
    streetName: string;
    buildingName?: string;
    floorNumber?: string;
    unitNumber?: string;
    postalCode: string;
}
