// This file was auto-generated by Fern from our API Definition.

export interface NoteDto {
    id: string;
    content: string;
    authorHciCode: string;
    authorName: string;
    createdAt: number;
    updatedAt: number;
}
