/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Category of the offering. Used to group offerings together.
 */
export type OfferingWithAllowedDtoCategory = "aac service" | "befriending";
export const OfferingWithAllowedDtoCategory = {
    AacService: "aac service",
    Befriending: "befriending",
} as const;
