/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Category of the offering. Used to group offerings together.
 */
export type OfferingDtoCategory = "aac" | "acp" | "gpfirst" | "ae";
export const OfferingDtoCategory = {
    Aac: "aac",
    Acp: "acp",
    Gpfirst: "gpfirst",
    Ae: "ae",
} as const;
