// This file was auto-generated by Fern from our API Definition.

/** Category of the offering. Used to group offerings together. */
export const OfferingDtoCategory = {
    Aac: "aac",
    Acp: "acp",
    Gpfirst: "gpfirst",
    Ae: "ae",
} as const;
export type OfferingDtoCategory = (typeof OfferingDtoCategory)[keyof typeof OfferingDtoCategory];
