// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface OfferingDto {
    id: string;
    /** Name of the offering - use these as labels */
    name: string;
    institutionHciCode: string;
    institution: ReferralExchange.InstitutionCoreDto;
    system: ReferralExchange.System;
    /** Clinical guidelines and other information which clinicians should read before proceeding with creating the referral. May contain URLs - should be rendered in a Linkify component */
    description: string;
    /** Whether the offering is able to receive new referrals currently */
    isActive: boolean;
    /** Whether this offering supports subsidized referrals. */
    isSubsidisable: boolean;
    timeslotPolicy: ReferralExchange.TimeslotPolicy;
    /** Category of the offering. Used to group offerings together. */
    category?: "aac";
}
