// This file was auto-generated by Fern from our API Definition.

export interface OfferingClinicianDto {
    /** Name of the clinician at the referral destination (the offering / receiving institution) */
    name: string;
}
