/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface PaginatedReferralsDto {
    data: ReferralExchange.ReferralDto[];
    metadata: ReferralExchange.PaginationMetadata;
}
