// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface PaginationMetadata {
    hasNext: boolean;
    totalCount: number;
    nextParams?: ReferralExchange.PaginatedQuery | undefined;
}
