// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface PaginatedReferralsDto {
    data: ReferralExchange.ReferralDto[];
    metadata: ReferralExchange.PaginationMetadata;
}
