/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface PaginatedQuery {
    /** Offset for pagination */
    offset?: Record<string, unknown>;
    /** Number of items per page */
    pageSize?: Record<string, unknown>;
}
