// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface PublicReferralDto {
    id: string;
    sender: ReferralExchange.InstitutionCoreDto;
    senderSystem: ReferralExchange.System;
    offering: ReferralExchange.OfferingDto;
    patient: ReferralExchange.GetReferralPatientDto;
    referringDoctor: ReferralExchange.ReferringDoctorDto;
    isSubsidised: boolean;
    isUrgent: boolean;
    /** Created at (ISO datetime) */
    createdAt: string;
    /** Updated at (ISO datetime) */
    updatedAt: string;
    formResponses: ReferralExchange.FormResponse[];
    /** List of forms required to complete the referral */
    forms?: ReferralExchange.Form[];
    attachments: ReferralExchange.AttachmentDto[];
    /** URL to view the referral */
    url?: string;
    /** Clinic license number */
    clinicLicenseNumber?: string;
    /** Clinic type */
    clinicType?: PublicReferralDto.ClinicType;
    /** Any clinical information that is relevant to the referral, e.g. medical history, drug allergies, treatment provided, etc. */
    clinicalInfo?: string;
}

export namespace PublicReferralDto {
    /** Clinic type */
    export const ClinicType = {
        ChasOnly: "CHAS-only",
        ChasAndHsg: "CHAS and HSG",
    } as const;
    export type ClinicType = (typeof ClinicType)[keyof typeof ClinicType];
}
