/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface PublicReferralDto {
    id: string;
    sender: ReferralExchange.InstitutionCoreDto;
    offering: ReferralExchange.OfferingFullDto;
    patient: ReferralExchange.GetReferralPatientDto;
    referringDoctor: ReferralExchange.PublicReferralDtoReferringDoctor;
    isSubsidised: boolean;
    isUrgent: boolean;
    /** Created at (ISO datetime) */
    createdAt: string;
    formResponses: ReferralExchange.FormResponse[];
}
