// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface ReferralLinkDto {
    type: ReferralExchange.ReferralLinkType;
    /** The ID of the referral */
    referralId: string;
    /** The URL of the link */
    url: string;
}
