// This file was auto-generated by Fern from our API Definition.

/** type of referral action */
export const ReferralActionLinkTypeV2 = {
    Amend: "amend",
    SelectTimeslot: "select-timeslot",
    FillSinghealthFormsg: "fill-singhealth-formsg",
    Attachment: "attachment",
    View: "view",
} as const;
export type ReferralActionLinkTypeV2 = (typeof ReferralActionLinkTypeV2)[keyof typeof ReferralActionLinkTypeV2];
