/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface ReferralDto {
    id: string;
    sender: ReferralExchange.InstitutionCoreDto;
    offering: ReferralExchange.OfferingFullDto;
    patient: ReferralExchange.GetReferralPatientDto;
    referringDoctor: ReferralExchange.ReferralDtoReferringDoctor;
    isSubsidised: boolean;
    isUrgent: boolean;
    /** Created at (ISO datetime) */
    createdAt: string;
    formResponses: ReferralExchange.FormResponse[];
    /** Form ID of the referral form */
    formId?: Record<string, unknown>;
    attachments: ReferralExchange.AttachmentDto[];
    status: ReferralExchange.ReferralDtoStatus;
    /** Timeslot start time (ISO datetime) */
    timeslotStartAt?: string;
    notes: ReferralExchange.NoteDto[];
    /** URL of the FormSG required to complete the referral */
    formUrl?: string;
}
