// This file was auto-generated by Fern from our API Definition.

/** type of referral link */
export const ReferralLinkType = {
    Upsert: "upsert",
    Amend: "amend",
    SelectTimeslot: "select-timeslot",
    FillSinghealthFormsg: "fill-singhealth-formsg",
} as const;
export type ReferralLinkType = (typeof ReferralLinkType)[keyof typeof ReferralLinkType];
