/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface ReferralDto {
    id: string;
    sender: ReferralExchange.InstitutionCoreDto;
    senderSystem: ReferralExchange.System;
    offering: ReferralExchange.OfferingDto;
    patient: ReferralExchange.GetReferralPatientDto;
    referringDoctor: ReferralExchange.ReferringDoctorDto;
    isSubsidised: boolean;
    isUrgent: boolean;
    /** Created at (ISO datetime) */
    createdAt: string;
    /** Updated at (ISO datetime) */
    updatedAt: string;
    formResponses: ReferralExchange.FormResponse[];
    /** List of forms required to complete the referral */
    forms?: ReferralExchange.Form[];
    attachments: ReferralExchange.AttachmentDto[];
    /** URL to view the referral */
    url?: string;
    /** Clinic license number */
    clinicLicenseNumber?: string;
    /** Clinic type */
    clinicType?: ReferralExchange.ReferralDtoClinicType;
    /** Any clinical information that is relevant to the referral, e.g. medical history, drug allergies, treatment provided, etc. */
    clinicalInfo?: string;
    status: ReferralExchange.ReferralDtoStatus;
    /** Timeslot start time (ISO datetime) */
    timeslotStartAt?: string;
    /** Appointment location */
    appointmentLocation?: string;
    notes: ReferralExchange.NoteDto[];
}
