/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface ReferrerStatusDto {
    /** Referrer ID (e.g. MCR number). */
    id: string;
    idType: ReferralExchange.ReferrerIdType;
    /** Institution HCI code. */
    institutionId: string;
    /** Timestamp when SingHealth whitelisted, or null. */
    singhealthWhitelistedAt?: number;
    /** Latest doctor email from referrals, or null. */
    latestDoctorEmail?: string;
}
