// This file was auto-generated by Fern from our API Definition.

/** type of referral link */
export const ReferralActionLinkType = {
    Amend: "amend",
    SelectTimeslot: "select-timeslot",
    FillSinghealthFormsg: "fill-singhealth-formsg",
} as const;
export type ReferralActionLinkType = (typeof ReferralActionLinkType)[keyof typeof ReferralActionLinkType];
