// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface ReferralUpsertLinkDto {
    /** The ID of the referral */
    referralId: string;
    /** The URL of the link */
    url: string;
    type: ReferralExchange.ReferralUpsertLinkType;
}
