// This file was auto-generated by Fern from our API Definition.

export const ReferralRole = {
    Sender: "sender",
    Receiver: "receiver",
} as const;
export type ReferralRole = (typeof ReferralRole)[keyof typeof ReferralRole];
