/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface ReferringDoctorDto {
    mcr: string;
    idType: ReferralExchange.ReferrerIdType;
    name: string;
    email: string;
    contactNumber: string;
}
