/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReferralRole = "sender" | "receiver";
export const ReferralRole = {
    Sender: "sender",
    Receiver: "receiver",
} as const;
