/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReferralDtoCoreStatus =
    | "draft"
    | "pending"
    | "confirmed"
    | "rejected"
    | "cancelled"
    | "sender-action-required";
export const ReferralDtoCoreStatus = {
    Draft: "draft",
    Pending: "pending",
    Confirmed: "confirmed",
    Rejected: "rejected",
    Cancelled: "cancelled",
    SenderActionRequired: "sender-action-required",
} as const;
