/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReferralDtoStatus =
    | "draft"
    | "created"
    | "processing-has"
    | "processing-pb"
    | "processing-ea"
    | "processing-bright"
    | "processing-fyi"
    | "processing-ngemr"
    | "pending-singhealth-formsg"
    | "pending-singhealth-call-centre"
    | "referral-confirmed-pending-appt"
    | "pending-email-ack"
    | "submitted-to-bright"
    | "pending-amend-timeslot"
    | "pending-acceptance"
    | "confirmed"
    | "sent"
    | "rejected"
    | "failed"
    | "pending-cancelled"
    | "cancelled";
export const ReferralDtoStatus = {
    Draft: "draft",
    Created: "created",
    ProcessingHas: "processing-has",
    ProcessingPb: "processing-pb",
    ProcessingEa: "processing-ea",
    ProcessingBright: "processing-bright",
    ProcessingFyi: "processing-fyi",
    ProcessingNgemr: "processing-ngemr",
    PendingSinghealthFormsg: "pending-singhealth-formsg",
    PendingSinghealthCallCentre: "pending-singhealth-call-centre",
    ReferralConfirmedPendingAppt: "referral-confirmed-pending-appt",
    PendingEmailAck: "pending-email-ack",
    SubmittedToBright: "submitted-to-bright",
    PendingAmendTimeslot: "pending-amend-timeslot",
    PendingAcceptance: "pending-acceptance",
    Confirmed: "confirmed",
    Sent: "sent",
    Rejected: "rejected",
    Failed: "failed",
    PendingCancelled: "pending-cancelled",
    Cancelled: "cancelled",
} as const;
