// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index";

export interface ReferralActionMetadataDto {
    type: ReferralExchange.ReferralActionLinkTypeV2;
    /** Human-readable label that can be displayed directly to users */
    label: string;
    attachment?: ReferralExchange.ReferralActionAttachmentDto | undefined;
}
