// This file was auto-generated by Fern from our API Definition.

/** type of referral link */
export const ReferralUpsertLinkType = {
    Upsert: "upsert",
} as const;
export type ReferralUpsertLinkType = (typeof ReferralUpsertLinkType)[keyof typeof ReferralUpsertLinkType];
