/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface ReferralActionLinkDto {
    /** The ID of the referral */
    referralId: string;
    /** The URL of the link */
    url: string;
    type: ReferralExchange.ReferralActionLinkType;
    /** Human-readable label that can be displayed directly to users */
    label: string;
}
