/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * type of referral link
 */
export type ReferralLinkType = "upsert" | "amend" | "select-timeslot";
export const ReferralLinkType = {
    Upsert: "upsert",
    Amend: "amend",
    SelectTimeslot: "select-timeslot",
} as const;
