// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface ReferringDoctorDto {
    mcr: string;
    idType: ReferralExchange.ReferrerIdType;
    name: string;
    email: string;
    contactNumber: string;
}
