/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of ID specified in referrerId.
 */
export type ReferrerIdType = "mcr" | "nric" | "email" | "brightUserId";
export const ReferrerIdType = {
    Mcr: "mcr",
    Nric: "nric",
    Email: "email",
    BrightUserId: "brightUserId",
} as const;
