/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RescheduleEventMetadata {
    appointmentTime: number;
    previousAppointmentTime?: Record<string, unknown>;
    systemUserIdentifier?: Record<string, unknown>;
}
