/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SubsidyEligibilityScheme = "chas" | "saf" | "none";
export const SubsidyEligibilityScheme = {
    Chas: "chas",
    Saf: "saf",
    None: "none",
} as const;
