// This file was auto-generated by Fern from our API Definition.

export interface SubsidyEligibility {
    isAllowed: boolean;
    /** Will be present if isAllowed is false */
    reason?: string;
    scheme: SubsidyEligibility.Scheme;
}

export namespace SubsidyEligibility {
    export const Scheme = {
        Chas: "chas",
        Saf: "saf",
        Hpb: "hpb",
        None: "none",
    } as const;
    export type Scheme = (typeof Scheme)[keyof typeof Scheme];
}
