/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type System = "HAS" | "PartnersBuddy" | "Refer" | "EmailAck" | "Bright" | "FYI";
export const System = {
    Has: "HAS",
    PartnersBuddy: "PartnersBuddy",
    Refer: "Refer",
    EmailAck: "EmailAck",
    Bright: "Bright",
    Fyi: "FYI",
} as const;
