// This file was auto-generated by Fern from our API Definition.

export const System = {
    Has: "HAS",
    PartnersBuddy: "PartnersBuddy",
    Refer: "Refer",
    EmailAck: "EmailAck",
    Bright: "Bright",
    Fyi: "FYI",
    Aac: "AAC",
    GpConnect: "GPConnect",
} as const;
export type System = (typeof System)[keyof typeof System];
