/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type System =
    | "HAS"
    | "PartnersBuddy"
    | "Refer"
    | "EmailAck"
    | "Bright"
    | "FYI"
    | "AAC"
    | "GPConnect"
    | "CLINICASSIST"
    | "LINKDOCTORS"
    | "GALENHEALTH"
    | "VANDACMS"
    | "MANADR"
    | "PLATO"
    | "RAFFLESMG"
    | "RUBICON"
    | "SGIMED"
    | "UNITEDCREST"
    | "IAPPS"
    | "UNOTECH"
    | "ZANDEN";
export const System = {
    Has: "HAS",
    PartnersBuddy: "PartnersBuddy",
    Refer: "Refer",
    EmailAck: "EmailAck",
    Bright: "Bright",
    Fyi: "FYI",
    Aac: "AAC",
    GpConnect: "GPConnect",
    Clinicassist: "CLINICASSIST",
    Linkdoctors: "LINKDOCTORS",
    Galenhealth: "GALENHEALTH",
    Vandacms: "VANDACMS",
    Manadr: "MANADR",
    Plato: "PLATO",
    Rafflesmg: "RAFFLESMG",
    Rubicon: "RUBICON",
    Sgimed: "SGIMED",
    Unitedcrest: "UNITEDCREST",
    Iapps: "IAPPS",
    Unotech: "UNOTECH",
    Zanden: "ZANDEN",
} as const;
