// This file was auto-generated by Fern from our API Definition.

/**
 * How timeslots are handled for this offering. Is enforced at validation.
 * timeslot-required: Timeslots must be selected when creating a referral.
 * optional-timeslots-and-urgentable: Timeslots are selectable but optional. If no timeslot is selected, the referral will be routed to a manual call-centre for scheduling. If you indicate `isUrgent: true`, the timeslot will be disregarded and referral will be sent to the call-centre for triage.
 * no-timeslots: Timeslots are not selectable for this offering. Calling the timeslot API will return an error.
 */
export const TimeslotPolicy = {
    TimeslotRequired: "timeslot-required",
    OptionalTimeslotsAndUrgentable: "optional-timeslots-and-urgentable",
    NoTimeslots: "no-timeslots",
} as const;
export type TimeslotPolicy = (typeof TimeslotPolicy)[keyof typeof TimeslotPolicy];
