/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface TimelineEventDto {
    type: ReferralExchange.TimelineEventDtoType;
    label: string;
    /** Additional (verbose) information, where relevant */
    description?: string;
    /** milliseconds since epoch */
    producedAt: number;
    /** System that produced the event */
    system: ReferralExchange.TimelineEventDtoSystem;
}
