// This file was auto-generated by Fern from our API Definition.

export interface Timeslot {
    /** Start time in milliseconds since epoch */
    from: number;
    /** End time in milliseconds since epoch */
    to: number;
}
