// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../index.js";

export interface TimelineEventDto {
    type: ReferralExchange.TimelineEventType;
    description: string;
    /** milliseconds since epoch */
    producedAt: number;
    /** System that produced the event */
    system: TimelineEventDto.System;
}

export namespace TimelineEventDto {
    /** System that produced the event */
    export const System = {
        Has: "HAS",
        PartnersBuddy: "PartnersBuddy",
        Refer: "Refer",
        EmailAck: "EmailAck",
        Bright: "Bright",
        Fyi: "FYI",
        Aac: "AAC",
        GpConnect: "GPConnect",
    } as const;
    export type System = (typeof System)[keyof typeof System];
}
