/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TimelineEventType =
    | "draft.created"
    | "draft.updated"
    | "draft.deleted"
    | "referral.created"
    | "referral.confirmed"
    | "referral.rejected"
    | "referral.pending-cancelled"
    | "referral.amended"
    | "referral.cancelled"
    | "referral.validated"
    | "referral.pending-email-ack"
    | "appt.confirmed"
    | "appt.rescheduled"
    | "appt.rejected"
    | "note.created"
    | "singhealth-patient-details.submitted"
    | "referral.ea-reminder-sent"
    | "referral.form-response-submitted"
    | "referral.back-to-draft";
export const TimelineEventType = {
    DraftCreated: "draft.created",
    DraftUpdated: "draft.updated",
    DraftDeleted: "draft.deleted",
    ReferralCreated: "referral.created",
    ReferralConfirmed: "referral.confirmed",
    ReferralRejected: "referral.rejected",
    ReferralPendingCancelled: "referral.pending-cancelled",
    ReferralAmended: "referral.amended",
    ReferralCancelled: "referral.cancelled",
    ReferralValidated: "referral.validated",
    ReferralPendingEmailAck: "referral.pending-email-ack",
    ApptConfirmed: "appt.confirmed",
    ApptRescheduled: "appt.rescheduled",
    ApptRejected: "appt.rejected",
    NoteCreated: "note.created",
    SinghealthPatientDetailsSubmitted: "singhealth-patient-details.submitted",
    ReferralEaReminderSent: "referral.ea-reminder-sent",
    ReferralFormResponseSubmitted: "referral.form-response-submitted",
    ReferralBackToDraft: "referral.back-to-draft",
} as const;
