/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * System that produced the event
 */
export type TimelineEventDtoSystem = "HAS" | "PartnersBuddy" | "Refer" | "EmailAck";
export const TimelineEventDtoSystem = {
    Has: "HAS",
    PartnersBuddy: "PartnersBuddy",
    Refer: "Refer",
    EmailAck: "EmailAck",
} as const;
