/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export type TimelineEventDtoMetadata =
    | ReferralExchange.CreatedEventMetadata
    | ReferralExchange.RejectedEventMetadata
    | ReferralExchange.NoteCreatedMetadata
    | ReferralExchange.RescheduleEventMetadata
    | ReferralExchange.SingHealthPatientDetailsMetadata
    | ReferralExchange.CancelledEventMetadata
    | ReferralExchange.ReferralAmendedMetadata
    | ReferralExchange.EaReminderSentMetadata;
