/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../index";

export interface TriggerEmailReminderBody {
    /** Email to cc the reminder to */
    ccEmail?: string;
    /** Email to send the reminder from */
    fromEmail?: string;
    /** Signature to be added to the email */
    signature?: ReferralExchange.EmailReminderSignature;
}
