// This file was auto-generated by Fern from our API Definition.

export interface UnauthorizedErrorBody {
    statusCode?: number | undefined;
    message?: string | undefined;
    error?: string | undefined;
}
