/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateEmailAckOfferingReq {
    /** Destination email list for the EmailAck offering */
    destinationEmails?: string[];
    /** Activity status of the offering */
    isActive?: boolean;
}
