// This file was auto-generated by Fern from our API Definition.

import type * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {
 *         requesterIdentifier: "requester@example.com",
 *         institutionIdType: "hci",
 *         institutionId: "institutionId"
 *     }
 */
export interface GetReferralActionLinkReq {
    /** Identifier for the individual requesting the referral. Preferred to be an email. */
    requesterIdentifier: string;
    institutionIdType: ReferralExchange.InstitutionIdType;
    /** The institution ID */
    institutionId: string;
    /** ID of the attachment. Required when the action link `type` is `attachment`. */
    attachmentId?: string;
}
