/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Patient residential status
 */
export type CreateLinkReqUpsertResidentialStatus = "SC" | "PR" | "Foreigner";
export const CreateLinkReqUpsertResidentialStatus = {
    Sc: "SC",
    Pr: "PR",
    Foreigner: "Foreigner",
} as const;
