/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Clinic type
 */
export type CreateLinkReqUpsertClinicType = "CHAS-only" | "CHAS and HSG";
export const CreateLinkReqUpsertClinicType = {
    ChasOnly: "CHAS-only",
    ChasAndHsg: "CHAS and HSG",
} as const;
