/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as ReferralExchange from "../../../../index";

/**
 * @example
 *     {}
 */
export interface PublicGetReferralRequest {
    additionalField?: ReferralExchange.AdditionalReferralField | ReferralExchange.AdditionalReferralField[];
}
