// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         referralId: "referralId",
 *         authorHciCode: "authorHciCode"
 *     }
 */
export interface CreateNoteReq {
    /** Referral ID */
    referralId: string;
    /** Note content - plaintext. */
    content?: string;
    /** Author HCI code. Must be already tied to your system. */
    authorHciCode: string;
}
