// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as ReferralExchange from "../../../index.js";

export declare namespace Public {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Public {
    protected readonly _options: Public.Options;

    constructor(_options: Public.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {ReferralExchange.GetReferralPublicRequest} request
     * @param {Public.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ReferralExchange.NotFoundError}
     *
     * @example
     *     await client.public.getReferral({
     *         referralId: "referralId"
     *     })
     */
    public getReferral(
        request: ReferralExchange.GetReferralPublicRequest,
        requestOptions?: Public.RequestOptions,
    ): core.HttpResponsePromise<ReferralExchange.PublicReferralDto> {
        return core.HttpResponsePromise.fromPromise(this.__getReferral(request, requestOptions));
    }

    private async __getReferral(
        request: ReferralExchange.GetReferralPublicRequest,
        requestOptions?: Public.RequestOptions,
    ): Promise<core.WithRawResponse<ReferralExchange.PublicReferralDto>> {
        const { referralId, additionalField } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (additionalField != null) {
            if (Array.isArray(additionalField)) {
                _queryParams.additionalField = additionalField.map((item) => item);
            } else {
                _queryParams.additionalField = additionalField;
            }
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ReferralExchangeEnvironment.SmartCms,
                `api/v1/public/referrals/${core.url.encodePathParam(referralId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as ReferralExchange.PublicReferralDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new ReferralExchange.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.ReferralExchangeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ReferralExchangeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ReferralExchangeTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/public/referrals/{referralId}.",
                );
            case "unknown":
                throw new errors.ReferralExchangeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { Authorization: apiKeyValue };
    }
}
