// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as ReferralExchange from "../../../index.js";

export declare namespace Eligibility {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Eligibility {
    protected readonly _options: Eligibility.Options;

    constructor(_options: Eligibility.Options = {}) {
        this._options = _options;
    }

    /**
     * @param {ReferralExchange.GetEligibilityRequest} request
     * @param {Eligibility.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link ReferralExchange.UnauthorizedError}
     *
     * @example
     *     await client.eligibility.get({
     *         referrerId: "referrerId",
     *         referrerIdType: "mcr",
     *         referrerInstitutionId: "referrerInstitutionId",
     *         uin: "uin",
     *         offeringId: "offeringId"
     *     })
     */
    public get(
        request: ReferralExchange.GetEligibilityRequest,
        requestOptions?: Eligibility.RequestOptions,
    ): core.HttpResponsePromise<ReferralExchange.EligibilityRes> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: ReferralExchange.GetEligibilityRequest,
        requestOptions?: Eligibility.RequestOptions,
    ): Promise<core.WithRawResponse<ReferralExchange.EligibilityRes>> {
        const { referrerId, referrerIdType, referrerInstitutionId, patientPostalCode, uin, offeringId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.referrerId = referrerId;
        _queryParams.referrerIdType = referrerIdType;
        _queryParams.referrerInstitutionId = referrerInstitutionId;
        if (patientPostalCode != null) {
            _queryParams.patientPostalCode = patientPostalCode;
        }

        _queryParams.uin = uin;
        _queryParams.offeringId = offeringId;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.ReferralExchangeEnvironment.SmartCms,
                "api/v1/eligibility",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as ReferralExchange.EligibilityRes, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new ReferralExchange.UnauthorizedError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.ReferralExchangeError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ReferralExchangeError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.ReferralExchangeTimeoutError("Timeout exceeded when calling GET /api/v1/eligibility.");
            case "unknown":
                throw new errors.ReferralExchangeError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { Authorization: apiKeyValue };
    }
}
