// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CreatingReferralsClient", () => {
    test("createUpsertLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionIdType: "hci",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            requesterIdentifier: "requester@example.com",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        };
        const rawResponseBody = { referralId: "referralId", url: "url", type: "upsert" };

        server
            .mockEndpoint()
            .post("/api/v1/links/upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.creatingReferrals.createUpsertLink({
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionIdType: "hci",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            requesterIdentifier: "requester@example.com",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createUpsertLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionIdType: "hci",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            requesterIdentifier: "requesterIdentifier",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/api/v1/links/upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.creatingReferrals.createUpsertLink({
                referrerInstitutionId: "referrerInstitutionId",
                referrerInstitutionIdType: "hci",
                referrerInstitutionName: "referrerInstitutionName",
                referrerId: "referrerId",
                requesterIdentifier: "requesterIdentifier",
                referrerIdType: "mcr",
                referrerName: "referrerName",
            });
        }).rejects.toThrow(ReferralExchange.BadRequestError);
    });

    test("createUpsertLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionIdType: "hci",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            requesterIdentifier: "requesterIdentifier",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/links/upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.creatingReferrals.createUpsertLink({
                referrerInstitutionId: "referrerInstitutionId",
                referrerInstitutionIdType: "hci",
                referrerInstitutionName: "referrerInstitutionName",
                referrerId: "referrerId",
                requesterIdentifier: "requesterIdentifier",
                referrerIdType: "mcr",
                referrerName: "referrerName",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
