// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Eligibility", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            referral: { isAllowed: true, reason: "reason" },
            subsidy: { isAllowed: true, reason: "reason", scheme: "chas" },
        };
        server
            .mockEndpoint()
            .get("/api/v1/eligibility")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.eligibility.get({
            referrerId: "referrerId",
            referrerIdType: "mcr",
            referrerInstitutionId: "referrerInstitutionId",
            uin: "uin",
            offeringId: "offeringId",
        });
        expect(response).toEqual({
            referral: {
                isAllowed: true,
                reason: "reason",
            },
            subsidy: {
                isAllowed: true,
                reason: "reason",
                scheme: "chas",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/eligibility")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.eligibility.get({
                referrerId: "referrerId",
                referrerIdType: "mcr",
                referrerInstitutionId: "referrerInstitutionId",
                uin: "uin",
                offeringId: "offeringId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
