// This file was auto-generated by Fern from our API Definition.

import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Health", () => {
    test("check", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { status: "ok" };
        server.mockEndpoint().get("/api/v1/health").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.health.check();
        expect(response).toEqual({
            status: "ok",
        });
    });
});
