// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Links", () => {
    test("createUpsertLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        };
        const rawResponseBody = { type: "upsert", referralId: "referralId", url: "url" };
        server
            .mockEndpoint()
            .post("/api/v1/links/upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.links.createUpsertLink({
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        });
        expect(response).toEqual({
            type: "upsert",
            referralId: "referralId",
            url: "url",
        });
    });

    test("createUpsertLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            referrerInstitutionId: "referrerInstitutionId",
            referrerInstitutionName: "referrerInstitutionName",
            referrerId: "referrerId",
            referrerIdType: "mcr",
            referrerName: "referrerName",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/v1/links/upsert")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.links.createUpsertLink({
                referrerInstitutionId: "referrerInstitutionId",
                referrerInstitutionName: "referrerInstitutionName",
                referrerId: "referrerId",
                referrerIdType: "mcr",
                referrerName: "referrerName",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
