// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Notes", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { authorHciCode: "authorHciCode" };
        const rawResponseBody = {
            id: "id",
            content: "content",
            authorHciCode: "authorHciCode",
            authorName: "authorName",
            createdAt: 1.1,
            updatedAt: 1.1,
        };
        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/notes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.notes.create({
            referralId: "referralId",
            authorHciCode: "authorHciCode",
        });
        expect(response).toEqual({
            id: "id",
            content: "content",
            authorHciCode: "authorHciCode",
            authorName: "authorName",
            createdAt: 1.1,
            updatedAt: 1.1,
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { authorHciCode: "authorHciCode" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/notes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.notes.create({
                referralId: "referralId",
                authorHciCode: "authorHciCode",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
