// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Offerings", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                isAllowed: true,
            },
        ];
        server.mockEndpoint().get("/api/v1/offerings").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.offerings.list({
            referrerId: "referrerId",
            referrerIdType: "mcr",
            referrerInstitutionId: "referrerInstitutionId",
        });
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                isAllowed: true,
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/api/v1/offerings").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.offerings.list({
                referrerId: "referrerId",
                referrerIdType: "mcr",
                referrerInstitutionId: "referrerInstitutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("ApiHoldingController_getRecommendedOffering (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            institutionHciCode: "institutionHciCode",
            institution: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            system: "HAS",
            description:
                "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
            isActive: true,
            isSubsidisable: true,
            timeslotPolicy: "timeslot-required",
            category: "aac",
        };
        server
            .mockEndpoint()
            .get("/api/v1/offerings/recommended")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.offerings.apiHoldingControllerGetRecommendedOffering({
            category: "aac",
            postalCode: "postalCode",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            institutionHciCode: "institutionHciCode",
            institution: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            system: "HAS",
            description:
                "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
            isActive: true,
            isSubsidisable: true,
            timeslotPolicy: "timeslot-required",
            category: "aac",
        });
    });

    test("ApiHoldingController_getRecommendedOffering (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/offerings/recommended")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.offerings.apiHoldingControllerGetRecommendedOffering({
                category: "aac",
                postalCode: "postalCode",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("ApiHoldingController_getRecommendedOffering (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/offerings/recommended")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.offerings.apiHoldingControllerGetRecommendedOffering({
                category: "aac",
                postalCode: "postalCode",
            });
        }).rejects.toThrow(ReferralExchange.NotFoundError);
    });

    test("listTimeslots (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = [{ from: 1714857600000, to: 1714861200000 }];
        server
            .mockEndpoint()
            .get("/api/v1/offerings/offeringId/timeslots")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.offerings.listTimeslots({
            offeringId: "offeringId",
            from: 1.1,
        });
        expect(response).toEqual([
            {
                from: 1714857600000,
                to: 1714861200000,
            },
        ]);
    });

    test("listTimeslots (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/offerings/offeringId/timeslots")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.offerings.listTimeslots({
                offeringId: "offeringId",
                from: 1.1,
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
