// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Public", () => {
    test("getReferral (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                },
                residentialStatus: "SC",
                isHsgEnrolled: true,
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [{ question: "question", id: "id", answer: "answer" }],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    isFilled: true,
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                },
            ],
            attachments: [{ url: "url", name: "ecg-report.png" }],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
        };
        server
            .mockEndpoint()
            .get("/api/v1/public/referrals/referralId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.public.getReferral({
            referralId: "referralId",
        });
        expect(response).toEqual({
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the guidelines of referrals to this SOC. https://go.gov.sg/refx-nuhs-gastro-guidelines",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                },
                residentialStatus: "SC",
                isHsgEnrolled: true,
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [
                {
                    question: "question",
                    id: "id",
                    answer: "answer",
                },
            ],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    isFilled: true,
                    formResponses: [
                        {
                            question: "question",
                            id: "id",
                            answer: "answer",
                        },
                    ],
                },
            ],
            attachments: [
                {
                    url: "url",
                    name: "ecg-report.png",
                },
            ],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
        });
    });

    test("getReferral (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/api/v1/public/referrals/referralId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.public.getReferral({
                referralId: "referralId",
            });
        }).rejects.toThrow(ReferralExchange.NotFoundError);
    });
});
