// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ReferralNotesClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            authorHciCode: "authorHciCode",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = {
            id: "id",
            content: "content",
            authorHciCode: "authorHciCode",
            authorName: "authorName",
            createdAt: 1.1,
            updatedAt: 1.1,
        };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/notes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.referralNotes.create("referralId", {
            authorHciCode: "authorHciCode",
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            authorHciCode: "authorHciCode",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/notes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.referralNotes.create("referralId", {
                authorHciCode: "authorHciCode",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
