// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("RetrievingReferralsClient", () => {
    test("listByInstitution (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    sender: {
                        hciCode: "hciCode",
                        name: "name",
                        block: "block",
                        streetName: "streetName",
                        buildingName: null,
                        floorNumber: null,
                        unitNumber: null,
                        postalCode: "postalCode",
                    },
                    senderSystem: "HAS",
                    offering: {
                        id: "id",
                        name: "name",
                        institutionHciCode: "institutionHciCode",
                        institution: {
                            hciCode: "hciCode",
                            name: "name",
                            block: "block",
                            streetName: "streetName",
                            buildingName: null,
                            floorNumber: null,
                            unitNumber: null,
                            postalCode: "postalCode",
                        },
                        system: "HAS",
                        description:
                            "Before proceeding with your referral, please refer to the [guidelines of referrals to this SOC](https://go.gov.sg/refx-nuhs-gastro-guidelines).",
                        isActive: true,
                        isSubsidisable: true,
                        timeslotPolicy: "timeslot-required",
                    },
                    patient: {
                        uin: "uin",
                        name: "name",
                        phoneNumber: "91234567",
                        dob: "1990-01-01",
                        gender: "Male",
                        chasStatus: null,
                    },
                    referringDoctor: {
                        mcr: "mcr",
                        idType: "mcr",
                        name: "name",
                        email: "email",
                        contactNumber: "contactNumber",
                    },
                    offeringClinician: { name: "name" },
                    isSubsidised: true,
                    isUrgent: true,
                    createdAt: "2024-05-01T00:00:00Z",
                    submittedAt: "2024-05-01T00:00:00Z",
                    updatedAt: "2024-05-01T00:00:00Z",
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                    forms: [
                        {
                            id: "id",
                            url: "url",
                            description: "description",
                            isFilled: true,
                            formResponses: [{ question: "question", id: "id", answer: "answer" }],
                        },
                    ],
                    attachments: [{ url: "url", name: "ecg-report.png" }],
                    url: "url",
                    clinicLicenseNumber: "clinicLicenseNumber",
                    clinicType: "CHAS-only",
                    clinicalInfo: "clinicalInfo",
                    coreStatus: "draft",
                    isCancellable: true,
                    canBackToDraft: true,
                    timeslotStartAt: "2024-05-01T00:00:00Z",
                    appointmentLocation: "appointmentLocation",
                    notes: [
                        {
                            id: "id",
                            content: "content",
                            authorHciCode: "authorHciCode",
                            authorName: "authorName",
                            createdAt: 1.1,
                            updatedAt: 1.1,
                        },
                    ],
                },
            ],
            metadata: { hasNext: true, totalCount: 1.1, nextParams: { offset: 1.1, pageSize: 1.1 } },
        };

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        expect(response).toEqual(rawResponseBody);
    });

    test("listByInstitution (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        }).rejects.toThrow(ReferralExchange.BadRequestError);
    });

    test("listByInstitution (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("listByInstitution (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        }).rejects.toThrow(ReferralExchange.ForbiddenError);
    });

    test("listByInstitution (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        }).rejects.toThrow(ReferralExchange.NotFoundError);
    });

    test("listByInstitution (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {};

        server
            .mockEndpoint()
            .get("/api/v1/institutions/hci/institutionId/referrals")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.listByInstitution("hci", "institutionId");
        }).rejects.toThrow(ReferralExchange.TooManyRequestsError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the [guidelines of referrals to this SOC](https://go.gov.sg/refx-nuhs-gastro-guidelines).",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                specialty: "specialty",
                nehrCode: "nehrCode",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    buildingName: "buildingName",
                    city: "city",
                    geographicalArea: "North",
                    country: "Singapore",
                },
                residentialStatus: "SC",
                nationality: "Singapore",
                race: "Chinese",
                email: "email",
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            offeringClinician: { name: "name" },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            submittedAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [{ question: "question", id: "id", answer: "answer" }],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    remark: "remark",
                    fields: [{ key: "value" }],
                    version: 1.1,
                    migrated: true,
                    isFilled: true,
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                },
            ],
            attachments: [{ url: "url", name: "ecg-report.png" }],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
            coreStatus: "draft",
            isCancellable: true,
            canBackToDraft: true,
            timeslotStartAt: "2024-05-01T00:00:00Z",
            appointmentLocation: "appointmentLocation",
            notes: [
                {
                    id: "id",
                    content: "content",
                    authorHciCode: "authorHciCode",
                    authorName: "authorName",
                    createdAt: 1.1,
                    updatedAt: 1.1,
                },
            ],
            timelineEvents: [
                {
                    type: "draft.created",
                    description: "PartnersBuddy rescheduled the appointment from 16 Dec, 10:00 PM to 21 Dec,11:00 PM",
                    producedAt: 1718764800000,
                    system: "HAS",
                },
            ],
            links: [{ referralId: "referralId", url: "url", type: "amend", label: "label" }],
            actions: [{ type: "amend", label: "label", attachment: { id: "id", uploadedAt: "2024-05-01T00:00:00Z" } }],
            appointments: [
                {
                    status: "scheduled",
                    institutionName: "institutionName",
                    specialtyName: "specialtyName",
                    subSpecialtyName: "subSpecialtyName",
                    visitDateTime: "2024-01-15T09:30:00Z",
                    isDischarged: true,
                    location: "location",
                },
            ],
            nehrForm: "nehrForm",
            nehrFormType: "nehrFormType",
        };

        server
            .mockEndpoint()
            .get("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.retrievingReferrals.get("referralId", {
            requesterIdentifier: "requester@example.com",
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.get("referralId", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.BadRequestError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.get("referralId", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.get("referralId", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.ForbiddenError);
    });

    test("get (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.get("referralId", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.NotFoundError);
    });

    test("getActionLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            requesterIdentifier: "requester@example.com",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = {
            type: "amend",
            label: "label",
            attachment: { id: "id", uploadedAt: "2024-05-01T00:00:00Z" },
            url: "url",
        };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/action-links/amend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.retrievingReferrals.getActionLink("referralId", "amend", {
            requesterIdentifier: "requester@example.com",
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getActionLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            requesterIdentifier: "requesterIdentifier",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/action-links/amend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.getActionLink("referralId", "amend", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.BadRequestError);
    });

    test("getActionLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            requesterIdentifier: "requesterIdentifier",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/action-links/amend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.getActionLink("referralId", "amend", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("getActionLink (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            requesterIdentifier: "requesterIdentifier",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/action-links/amend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.getActionLink("referralId", "amend", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.ForbiddenError);
    });

    test("getActionLink (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = {
            requesterIdentifier: "requesterIdentifier",
            institutionIdType: "hci",
            institutionId: "institutionId",
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/action-links/amend")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.retrievingReferrals.getActionLink("referralId", "amend", {
                requesterIdentifier: "requesterIdentifier",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.NotFoundError);
    });
});
