// This file was auto-generated by Fern from our API Definition.

import * as ReferralExchange from "../../src/api/index";
import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UpdatingReferralsClient", () => {
    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the [guidelines of referrals to this SOC](https://go.gov.sg/refx-nuhs-gastro-guidelines).",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                specialty: "specialty",
                nehrCode: "nehrCode",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    buildingName: "buildingName",
                    city: "city",
                    geographicalArea: "North",
                    country: "Singapore",
                },
                residentialStatus: "SC",
                nationality: "Singapore",
                race: "Chinese",
                email: "email",
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            offeringClinician: { name: "name" },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            submittedAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [{ question: "question", id: "id", answer: "answer" }],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    remark: "remark",
                    fields: [{ key: "value" }],
                    version: 1.1,
                    migrated: true,
                    isFilled: true,
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                },
            ],
            attachments: [{ url: "url", name: "ecg-report.png" }],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
            coreStatus: "draft",
            isCancellable: true,
            canBackToDraft: true,
            timeslotStartAt: "2024-05-01T00:00:00Z",
            appointmentLocation: "appointmentLocation",
            notes: [
                {
                    id: "id",
                    content: "content",
                    authorHciCode: "authorHciCode",
                    authorName: "authorName",
                    createdAt: 1.1,
                    updatedAt: 1.1,
                },
            ],
        };

        server
            .mockEndpoint()
            .delete("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.updatingReferrals.delete("referralId", {
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/referrals/referralId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updatingReferrals.delete("referralId", {
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("cancel (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { cancelNote: "cancelNote", institutionIdType: "hci", institutionId: "institutionId" };
        const rawResponseBody = {
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the [guidelines of referrals to this SOC](https://go.gov.sg/refx-nuhs-gastro-guidelines).",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                specialty: "specialty",
                nehrCode: "nehrCode",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    buildingName: "buildingName",
                    city: "city",
                    geographicalArea: "North",
                    country: "Singapore",
                },
                residentialStatus: "SC",
                nationality: "Singapore",
                race: "Chinese",
                email: "email",
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            offeringClinician: { name: "name" },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            submittedAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [{ question: "question", id: "id", answer: "answer" }],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    remark: "remark",
                    fields: [{ key: "value" }],
                    version: 1.1,
                    migrated: true,
                    isFilled: true,
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                },
            ],
            attachments: [{ url: "url", name: "ecg-report.png" }],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
            coreStatus: "draft",
            isCancellable: true,
            canBackToDraft: true,
            timeslotStartAt: "2024-05-01T00:00:00Z",
            appointmentLocation: "appointmentLocation",
            notes: [
                {
                    id: "id",
                    content: "content",
                    authorHciCode: "authorHciCode",
                    authorName: "authorName",
                    createdAt: 1.1,
                    updatedAt: 1.1,
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.updatingReferrals.cancel("referralId", {
            cancelNote: "cancelNote",
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("cancel (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { cancelNote: "cancelNote", institutionIdType: "hci", institutionId: "institutionId" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/cancel")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updatingReferrals.cancel("referralId", {
                cancelNote: "cancelNote",
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });

    test("backToDraft (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { institutionIdType: "hci", institutionId: "institutionId" };
        const rawResponseBody = {
            id: "id",
            sender: {
                hciCode: "hciCode",
                name: "name",
                block: "block",
                streetName: "streetName",
                buildingName: "buildingName",
                floorNumber: "floorNumber",
                unitNumber: "unitNumber",
                postalCode: "postalCode",
            },
            senderSystem: "HAS",
            offering: {
                id: "id",
                name: "name",
                institutionHciCode: "institutionHciCode",
                institution: {
                    hciCode: "hciCode",
                    name: "name",
                    block: "block",
                    streetName: "streetName",
                    buildingName: "buildingName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    postalCode: "postalCode",
                },
                system: "HAS",
                description:
                    "Before proceeding with your referral, please refer to the [guidelines of referrals to this SOC](https://go.gov.sg/refx-nuhs-gastro-guidelines).",
                isActive: true,
                isSubsidisable: true,
                timeslotPolicy: "timeslot-required",
                category: "aac",
                specialty: "specialty",
                nehrCode: "nehrCode",
            },
            patient: {
                uin: "uin",
                name: "name",
                phoneNumber: "91234567",
                dob: "1990-01-01",
                gender: "Male",
                address: {
                    postalCode: "postalCode",
                    block: "block",
                    streetName: "streetName",
                    floorNumber: "floorNumber",
                    unitNumber: "unitNumber",
                    buildingName: "buildingName",
                    city: "city",
                    geographicalArea: "North",
                    country: "Singapore",
                },
                residentialStatus: "SC",
                nationality: "Singapore",
                race: "Chinese",
                email: "email",
                chasStatus: "chasStatus",
            },
            referringDoctor: {
                mcr: "mcr",
                idType: "mcr",
                name: "name",
                email: "email",
                contactNumber: "contactNumber",
            },
            offeringClinician: { name: "name" },
            isSubsidised: true,
            isUrgent: true,
            createdAt: "2024-05-01T00:00:00Z",
            submittedAt: "2024-05-01T00:00:00Z",
            updatedAt: "2024-05-01T00:00:00Z",
            formResponses: [{ question: "question", id: "id", answer: "answer" }],
            forms: [
                {
                    id: "id",
                    url: "url",
                    description: "description",
                    remark: "remark",
                    fields: [{ key: "value" }],
                    version: 1.1,
                    migrated: true,
                    isFilled: true,
                    formResponses: [{ question: "question", id: "id", answer: "answer" }],
                },
            ],
            attachments: [{ url: "url", name: "ecg-report.png" }],
            url: "url",
            clinicLicenseNumber: "clinicLicenseNumber",
            clinicType: "CHAS-only",
            clinicalInfo: "clinicalInfo",
            coreStatus: "draft",
            isCancellable: true,
            canBackToDraft: true,
            timeslotStartAt: "2024-05-01T00:00:00Z",
            appointmentLocation: "appointmentLocation",
            notes: [
                {
                    id: "id",
                    content: "content",
                    authorHciCode: "authorHciCode",
                    authorName: "authorName",
                    createdAt: 1.1,
                    updatedAt: 1.1,
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/back-to-draft")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.updatingReferrals.backToDraft("referralId", {
            institutionIdType: "hci",
            institutionId: "institutionId",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("backToDraft (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ maxRetries: 0, environment: server.baseUrl });
        const rawRequestBody = { institutionIdType: "hci", institutionId: "institutionId" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/referrals/referralId/back-to-draft")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.updatingReferrals.backToDraft("referralId", {
                institutionIdType: "hci",
                institutionId: "institutionId",
            });
        }).rejects.toThrow(ReferralExchange.UnauthorizedError);
    });
});
