// This file was auto-generated by Fern from our API Definition.

import { ReferralExchangeClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Webhooks", () => {
    test("submitSingHealthFormsg", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/api/v1/webhooks/formsg/singhealth-profile").respondWith().statusCode(200).build();

        const response = await client.webhooks.submitSingHealthFormsg();
        expect(response).toEqual(undefined);
    });

    test("submitFormsg", async () => {
        const server = mockServerPool.createServer();
        const client = new ReferralExchangeClient({ apiKey: "test", environment: server.baseUrl });

        server
            .mockEndpoint()
            .post("/api/v1/webhooks/formsg/form-submission/formId")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.webhooks.submitFormsg({
            formId: "formId",
        });
        expect(response).toEqual(undefined);
    });
});
