/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { RetrievingReferrals } from "./api/resources/retrievingReferrals/client/Client";
import { UpdatingReferrals } from "./api/resources/updatingReferrals/client/Client";
import { ReferralNotes } from "./api/resources/referralNotes/client/Client";
import { CreatingReferrals } from "./api/resources/creatingReferrals/client/Client";

export declare namespace ReferralExchangeClient {
    export interface Options {
        environment?: core.Supplier<environments.ReferralExchangeEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class ReferralExchangeClient {
    protected _retrievingReferrals: RetrievingReferrals | undefined;
    protected _updatingReferrals: UpdatingReferrals | undefined;
    protected _referralNotes: ReferralNotes | undefined;
    protected _creatingReferrals: CreatingReferrals | undefined;

    constructor(protected readonly _options: ReferralExchangeClient.Options) {}

    public get retrievingReferrals(): RetrievingReferrals {
        return (this._retrievingReferrals ??= new RetrievingReferrals(this._options));
    }

    public get updatingReferrals(): UpdatingReferrals {
        return (this._updatingReferrals ??= new UpdatingReferrals(this._options));
    }

    public get referralNotes(): ReferralNotes {
        return (this._referralNotes ??= new ReferralNotes(this._options));
    }

    public get creatingReferrals(): CreatingReferrals {
        return (this._creatingReferrals ??= new CreatingReferrals(this._options));
    }
}
