// This file was auto-generated by Fern from our API Definition.

export const ReferralExchangeEnvironment = {
    SmartCms: "https://dummy-url-see-smartcms-spec",
    Production: "https://refer.health.gov.sg",
    Staging: "https://refer-staging.health.gov.sg",
} as const;

export type ReferralExchangeEnvironment =
    | typeof ReferralExchangeEnvironment.SmartCms
    | typeof ReferralExchangeEnvironment.Production
    | typeof ReferralExchangeEnvironment.Staging;
