/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ReferralExchangeEnvironment = {
    Production: "https://refer.health.gov.sg",
    Staging: "https://refer-staging.health.gov.sg",
} as const;

export type ReferralExchangeEnvironment =
    | typeof ReferralExchangeEnvironment.Production
    | typeof ReferralExchangeEnvironment.Staging;
