/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApiHoldingControllerGetRecommendedOfferingRequestCategory = "aac service" | "befriending";
export const ApiHoldingControllerGetRecommendedOfferingRequestCategory = {
    AacService: "aac service",
    Befriending: "befriending",
} as const;
