/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ApiHoldingControllerGetRecommendedOfferingRequestCategory = "aac" | "acp";
export const ApiHoldingControllerGetRecommendedOfferingRequestCategory = {
    Aac: "aac",
    Acp: "acp",
} as const;
