/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReferralsListRequestStatusItem = "draft" | "pending" | "confirmed" | "rejected" | "cancelled";
export const ReferralsListRequestStatusItem = {
    Draft: "draft",
    Pending: "pending",
    Confirmed: "confirmed",
    Rejected: "rejected",
    Cancelled: "cancelled",
} as const;
