/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ReferralsListRequestRole = "sender" | "receiver";
export const ReferralsListRequestRole = {
    Sender: "sender",
    Receiver: "receiver",
} as const;
